### ISSUE TITLE
the issue about zipdata

### ISSUE THREAD

**Issue by git-mengmeng** [christopherjenness/NBA-player-movement#6]
File "D:\new win10\workspace\hupu\third\game\game.py", line 112, in _get_tracking_data
    os.remove("./temp/zipdata")
FileNotFoundError: [WinError 2] 系统找不到指定的文件（system cant find the file）。: './temp/zipdata'

**Comment by git-mengmeng** [comment]
子目录或文件 temp 已经存在。(the sub directory or file has existed)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0curl: (6) Could not resolve host: None

7-Zip (A) 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18


Error:
cannot find archive
Traceback (most recent call last):
  File "D:\new win10\workspace\hupu\third\game\test.py", line 2, in <module>
    game = Game('01.08.2016', 'POR', 'GSW')
  File "D:\new win10\workspace\hupu\third\game\game.py", line 84, in __init__
    self._get_tracking_data()
  File "D:\new win10\workspace\hupu\third\game\game.py", line 112, in _get_tracking_data
    os.remove("./temp/zipdata")
FileNotFoundError: [WinError 2] 系统找不到指定的文件。: './temp/zipdata'

Here is the Log in the console
